image:
  file: .gitpod.Dockerfile

tasks:
  # Tools
  - init: npm install
  # Datasette
  - command: cd datasette && datasette serve -h 0.0.0.0 -p 8001 --metadata metadata.json data/links.db
    openMode: split-right
  # 11ty
  - init: cd 11ty && npm install
    command: cd 11ty && npm run dev
    openMode: split-left

ports:
  - port: 8080
    onOpen: notify
    visibility: public
  - port: 3001
    onOpen: ignore
    visibility: private
  - port: 8001
    onOpen: notify
    visibility: public

github:
  prebuilds:
    master: true