image:
  file: .gitpod.Dockerfile

tasks:
  - command: datasette serve -h 0.0.0.0 -p 8001 data/links.db

ports:
  - port: 8001
    onOpen: open-preview
    visibility: public

github:
  prebuilds:
    master: true