image:
  file: .gitpod.Dockerfile

tasks:
  - name: Datasette
    init: |
      cd ${GITPOD_REPO_ROOT}/datasette
      pip install -r requirements.txt
    command: |
      cd ${GITPOD_REPO_ROOT}/datasette
      datasette serve -h 0.0.0.0 -p 8001 --metadata metadata.json ../packages/web/public/data/links.db
  - name: Webserver
    init: |
      npm install
      npm run build --workspaces
    command: npm run dev --workspace packages/web
    openMode: tab-after

ports:
  # Datasette
  - port: 8001
    onOpen: notify
    visibility: public
  # NextJS
  - port: 3000
    onOpen: ignore
    visibility: public

github:
  prebuilds:
    master: true
