name: Build
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Upgrade to NPM 7
        run: npm install -g npm@7

      - name: NPM install
        run: npm ci

      - name: Compile
        run: npm run build --workspaces

      - name: Tests - Unit
        run: npm run test:unit --workspaces

      - name: Tests - E2E
        run: npm run test:e2e --workspaces
